# permissions for end users to edit portscanpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portscanpolicy-editor-role
rules:
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - portscanpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - portscanpolicies/status
  verbs:
  - get
