apiVersion: policy.open-cluster-management.io/v1alpha1
kind: PortScanPolicy
metadata:
  name: portscanpolicy-sample
spec:
  namespaceSelector:
    include: ["*"]
    exclude: []
  scanTargetKinds:
  - "services"
  rules:
  - name: "MinimumCipherGrade"
    value: "@"
