//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortDiscoveryOption) DeepCopyInto(out *PortDiscoveryOption) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortDiscoveryOption.
func (in *PortDiscoveryOption) DeepCopy() *PortDiscoveryOption {
	if in == nil {
		return nil
	}
	out := new(PortDiscoveryOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortScanPolicy) DeepCopyInto(out *PortScanPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortScanPolicy.
func (in *PortScanPolicy) DeepCopy() *PortScanPolicy {
	if in == nil {
		return nil
	}
	out := new(PortScanPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PortScanPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortScanPolicyList) DeepCopyInto(out *PortScanPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PortScanPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortScanPolicyList.
func (in *PortScanPolicyList) DeepCopy() *PortScanPolicyList {
	if in == nil {
		return nil
	}
	out := new(PortScanPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PortScanPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortScanPolicySpec) DeepCopyInto(out *PortScanPolicySpec) {
	*out = *in
	in.PolicyCoreSpec.DeepCopyInto(&out.PolicyCoreSpec)
	if in.ScanTargetKinds != nil {
		in, out := &in.ScanTargetKinds, &out.ScanTargetKinds
		*out = make([]ScanTargetKind, len(*in))
		copy(*out, *in)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]Rule, len(*in))
		copy(*out, *in)
	}
	out.ScanInterval = in.ScanInterval
	if in.PortDiscovery != nil {
		in, out := &in.PortDiscovery, &out.PortDiscovery
		*out = make([]PortDiscoveryOption, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortScanPolicySpec.
func (in *PortScanPolicySpec) DeepCopy() *PortScanPolicySpec {
	if in == nil {
		return nil
	}
	out := new(PortScanPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortScanPolicyStatus) DeepCopyInto(out *PortScanPolicyStatus) {
	*out = *in
	in.PolicyCoreStatus.DeepCopyInto(&out.PolicyCoreStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortScanPolicyStatus.
func (in *PortScanPolicyStatus) DeepCopy() *PortScanPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PortScanPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rule) DeepCopyInto(out *Rule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rule.
func (in *Rule) DeepCopy() *Rule {
	if in == nil {
		return nil
	}
	out := new(Rule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanInterval) DeepCopyInto(out *ScanInterval) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanInterval.
func (in *ScanInterval) DeepCopy() *ScanInterval {
	if in == nil {
		return nil
	}
	out := new(ScanInterval)
	in.DeepCopyInto(out)
	return out
}
